codecov:
  token: 9c92b00a-43e8-4dd3-b455-196052f16f86

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true
    patch: true
    changes: true

  ignore:
    - "Sources/SwifterSwift/Deprecated/*"
    - "Sources/SwifterSwift/*/Deprecated/*"
    - "Tests/**/*"
